### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by FGRibreau** [chameleonbr/node-red-contrib-redis#1]
As a user of node-red, I was waiting for this one! This is so cool @chameleonbr !

This connector will be shared in our next [RedisWeekly](http://redisweekly.com) this morning!

**Comment by chameleonbr** [comment]
Thank you, NodeRED community had already made a node to the redis, but I thought features like queuing and free execution of commands were missing.
The next thing I want to do is to build redis lua scripts within the nodered.

**Comment by chameleonbr** [comment]
Now with lua scripting!

**Comment by FGRibreau** [comment]
Nice @chameleonbr !
