### ISSUE TITLE
Redis CMD Node gives "Error: Connection is closed."

### ISSUE THREAD

**Issue by RaymondMouthaan** [chameleonbr/node-red-contrib-redis#12]
Hello,

I try to use the Redis cmd node to get a key value pair, but i get "Error: Connection is closed." instead.

My flow is as follows:

`[{"id":"f9420b3b.0915","type":"redis-command","z":"e695df03.a53db","server":"2f8aab8e.a11344","command":"get","name":"","topic":"","x":480,"y":560,"wires":[["d7b27ce1.506a6"]]},{"id":"5e11adb1.64590c","type":"inject","z":"e695df03.a53db","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":180,"y":560,"wires":[["d10267ea.6a83d"]]},{"id":"d7b27ce1.506a6","type":"debug","z":"e695df03.a53db","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":650,"y":560,"wires":[]},{"id":"d10267ea.6a83d","type":"function","z":"e695df03.a53db","name":"","func":"msg.payload = ['key', 'value'];\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":560,"wires":[["f9420b3b.0915"]]},{"id":"2f8aab8e.a11344","type":"redis-config","z":"","host":"10.1.0.105","port":"6379","dbase":"0","pass":""}]`

Any help / example would be appreciated.

**Comment by chameleonbr** [comment]
This is a race condition case. See if the last version this bug remains.
