### ISSUE TITLE
Support for transactions

### ISSUE THREAD

**Issue by thommc** [chameleonbr/node-red-contrib-redis#13]
Nice library, thank you.

Tried using a redis-cmd node to send MULTI, then another for a ZADD, another for HMSET, then another for EXEC.

Looking at the source for your module, it looks like it closes the connection after each command, and I'm guessing that aborts the transaction in Redis.  Any tips?

While I'm here, is there a way to pipeline too?

Cheers

**Comment by kenime** [comment]
I think the connection is only closed when node close event is emitted, i.e stopping flow.

**Comment by chameleonbr** [comment]
New node called "Instance Node" solve this issue, now you could create a redis client instance and share globally or in flow. See the example on README.md.
