### ISSUE TITLE
Memory leak with BLPOP

### ISSUE THREAD

**Issue by rjbaat** [chameleonbr/node-red-contrib-redis#16]
Hi All,
i have a flow that uses the redis out with RPUSH to fill a list and another flow to empty the list with BLPOP. Now this principle works oke. Only the flows that get the stored data (BLPOP) from the list will grow in memory over time (up to 1.1GB). Until the server is out of memory. But i didn't let that happen due to a manual restart in time.

I use docker for both (latest) redis and node red. Also i don't get errors related to this issue. Is there a way to solve this?

**Comment by chameleonbr** [comment]
I found some bugs in "Redis in Node" and in the latest version I rewrote it.
