### ISSUE TITLE
lrange

### ISSUE THREAD

**Issue by ggocsei** [chameleonbr/node-red-contrib-redis#28]
Hi!

Thanks for this plugin, you saved my life! :) Now I have some info shortage.
I can't figuring out how i have to setup the redis cmd node for lrange. I always get 
"ReplyError: ERR wrong number of arguments for 'lrange' command"
What's the proper syntax in json for exaple for this command: lrange sensors 0 0 ?

 Thanks a lot!

Gabor

**Comment by chameleonbr** [comment]
Redis cmd receives an array as parameter in this case parameters is ['sensors',0,0].
