### ISSUE TITLE
Some questions regarding redis instances and separate databases

### ISSUE THREAD

**Issue by svdasein** [chameleonbr/node-red-contrib-redis#30]
A few questions for you if you have a moment to answer them:

* What's the purpose of the redis instance object?
* What is the right way to use the redis instance object?
* redis instance objects have a drop down that select scope (global/flow) - what does that actually affect?
* What is the right way to work with multiple redis databases (redis-cli -n # )

I am asking these questions because I'm running into an issue where I sometimes cannot seem to communicate to a particular database in redis.  I am connected to e.g. database 9 and can talk to it, but for some reason on certain flows I cannot talk to database 8.

Thanks for your time.

edit: I just hacked in a forced "true" for the "block" attribute of the redis command node type. having done that, my problems have gone away.  So I suspect something is really going on with scoping & connection sharing (as I understand if if "block" is true each node gets its own connection to redis)

**Comment by chameleonbr** [comment]
Hi with redis instance you could add ioredis connection to function node, example code:

let redisFromFlow = flow.get("redis"); //now yout could use any method from ioredis client

let redisFromGlobal = global.get("redisGlobal");

I will test if my module have some bug related to this.
