### ISSUE TITLE
Connect to remote redis

### ISSUE THREAD

**Issue by dm7pwnage** [chameleonbr/node-red-contrib-redis#36]
Hi,

would you please provide an example how to connect to a remote redis on a different port including a password?

Whatever combination I enter in the field "server" I get the error: "Error: connect ECONNREFUSED 127.0.0.1:6379"

Thank you in advance!

Kind regards

**Comment by chameleonbr** [comment]
Please see #35 some options to configure your redis server.  Duplicate of #35.

**Comment by chameleonbr** [comment]
Duplicate of #35.

**Comment by chameleonbr** [comment]
See the IORedis constructor parameters, https://github.com/luin/ioredis#connect-to-redis.

**Comment by dm7pwnage** [comment]
Thank you for your quick response.
