### ISSUE TITLE
error shows while deploying and when setting to HMSET method

### ISSUE THREAD

**Issue by nadeerck2020** [chameleonbr/node-red-contrib-redis#39]
Error showing like this.
"Missing options in the redis config - Are you upgrading from old version?"

<img width="166" alt="redis issue" src="https://user-images.githubusercontent.com/65544497/88759178-d4405f00-d187-11ea-8f6a-1ae6ecaf0fdd.PNG">

when calling hmset method it shows error like this.
 "TypeError: Cannot read property 'call' of undefined"

**Comment by chameleonbr** [comment]
I'm using last version of module and function works... see my flow example:

`
[{"id":"f37fd098.4664a","type":"inject","z":"55c94707.621bd8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[\"k1\",\"v1\",\"k2\",\"v2\"]","payloadType":"json","x":240,"y":180,"wires":[["985a561e.606b68"]]},{"id":"985a561e.606b68","type":"redis-command","z":"55c94707.621bd8","server":"b9b5bedb.89eda","command":"HMSET","name":"","topic":"hash","params":"[]","paramsType":"json","payloadType":"json","block":false,"x":450,"y":180,"wires":[["7151bdc7.ab2114"]]},{"id":"7151bdc7.ab2114","type":"debug","z":"55c94707.621bd8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":650,"y":180,"wires":[]},{"id":"b9b5bedb.89eda","type":"redis-config","z":"","name":"Local","options":"{\"host\":\"localhost\",\"port\":6379}","cluster":false,"optionsType":"json"}]
`
