### ISSUE TITLE
Unable to update redis-config in > v1.1.6

### ISSUE THREAD

**Issue by faisalchishtii** [chameleonbr/node-red-contrib-redis#42]
In v1.1.6 and below, I can just update the redis-config by clicking the below pencil icon.

![image](https://user-images.githubusercontent.com/26409919/93557257-2471bb80-f998-11ea-8126-0dbe8d40031c.png)

On clicking the pencil icon, I see below fields that I can update and it works well.

![image](https://user-images.githubusercontent.com/26409919/93557293-45d2a780-f998-11ea-904e-b25ac0849768.png)

However, in >1.1.6, when I click the pencil icon, I just see below fields. How do I add the host, port and other details? I checked the documentation but did not find any reference. 

![image](https://user-images.githubusercontent.com/26409919/93557455-a1049a00-f998-11ea-9868-02ffce2f457b.png)

**Comment by chameleonbr** [comment]
On updated version of Redis Node Configuration shows the options:
![image](https://user-images.githubusercontent.com/889458/93607158-56d2e700-f99f-11ea-8d27-f61264096216.png)
and you need to select ENV, and the env var need to be string connection pattern(https://github.com/luin/ioredis#connect-to-redis) as this redis://:authpassword@127.0.0.1:6380/4

**Comment by faisalchishtii** [comment]
@chameleonbr I can't find the dropdown for Options. It appears to be a text field. I am using **v1.3.7** and Node-RED **0.18.3**

![image](https://user-images.githubusercontent.com/26409919/93658607-b80bc080-fa5a-11ea-9e21-ce84cb974bc3.png)

**Comment by chameleonbr** [comment]
Hi @faisalchishtii, if you are not able to update NodeRED I recommend you to keep old version of this module. I use NodeRED since 0.1x and I’m updating NodeRED and modules since then and everything is working.

**Comment by chameleonbr** [comment]
Ever is more easy an old module works with new NodeRED version then new modules works with old NodeRED version.

**Comment by faisalchishtii** [comment]
Decided to upgrade Node-RED. Thanks!
