### ISSUE TITLE
Incomming topic is overwriting the topic set in the node

### ISSUE THREAD

**Issue by qwaxys** [chameleonbr/node-red-contrib-redis#46]
https://github.com/chameleonbr/node-red-contrib-redis/blob/1193796700f5874c8e33e51ea4f3f26bcf529b37/redis.js#L161

The incoming/msg topic is overwriting the topic set in the node.

Should this:
`if (msg.topic !== undefined && msg.topic !== "") {`
not be:
`if (msg.topic !== undefined && msg.topic == "") {`
?

**Comment by chameleonbr** [comment]
The default topic is configured in node, if you need change topic fill in msg.topic and the "default topic" is overrided, if you need ever keep the default topic, only clean msg.topic before pass the node.
