### ISSUE TITLE
Redis Cmd/Lua connection program when using multiple redis server

### ISSUE THREAD

**Issue by Easyfilecopy** [chameleonbr/node-red-contrib-redis#47]
Produce
one rmt, one local
Use Get Cmd to retrieve local var. It always uses rmt redis server.
========== FIX ==========
  function RedisCmd(n) {
    RED.nodes.createNode(this, n);
    this.server = RED.nodes.getNode(n.server);
    this.command = n.command;
    this.name = n.name;
    this.topic = n.topic;
    this.params = n.params;
    var node = this;
    this.block = n.block || false;
//    let id = this.block ? n.id : n.server.name;
    let id = this.block ? n.id : n.server;

**Comment by chameleonbr** [comment]
Hi @Easyfilecopy I will change the code and test. Thanks for use this module.
