### ISSUE TITLE
PUB SUB not working

### ISSUE THREAD

**Issue by mpanichellasura** [chameleonbr/node-red-contrib-redis#49]
Hi!, I need create a pub sub in node-red flow, but wiwh publish and subscribe not working, i never arrive a message.

I try do a PUT and GET, and the message is saved to Redis, but never GET the message.

If i execute the command GET i recive null objects

I try multiple options but not working, i dont know that is a bug, but the documentation cant help me to find a solution. can you help me? thanks

**Comment by chameleonbr** [comment]
Please, first, on redis-cli use the "monitor" command to see if the node-red is connecting on redis, all commands that redis receives is shown on the console.
If the error persists  send me the JSON code of your flow.

**Comment by chameleonbr** [comment]
Please check instructions showed above and if the problem persists reopen the issue.
