### ISSUE TITLE
How to get message payload from a REDIS-IN? Any example?

### ISSUE THREAD

**Issue by vfonsecapv** [chameleonbr/node-red-contrib-redis#7]

**Comment by vfonsecapv** [comment]
I get that message:

"TypeError: Cannot create property '_msgid' on string 'hello'"

**Comment by chameleonbr** [comment]
Hi, what is the message that you trying to send?

See this example of use:

[{"id":"32c711c2.fdc16e","type":"redis-in","z":"6d2f56bc.3a80c8","server":"e29b26e8.c5f788","command":"blpop","name":"","topic":"test","timeout":0,"x":520,"y":360,"wires":[["1658906d.362b5"]]},{"id":"3a155f79.50404","type":"redis-out","z":"6d2f56bc.3a80c8","server":"e29b26e8.c5f788","command":"rpush","name":"","topic":"test","x":750,"y":320,"wires":[]},{"id":"7f8caafd.493114","type":"inject","z":"6d2f56bc.3a80c8","name":"","topic":"","payload":"{\"lala\":123}","payloadType":"json","repeat":"","crontab":"","once":false,"x":520,"y":300,"wires":[["3a155f79.50404"]]},{"id":"1658906d.362b5","type":"debug","z":"6d2f56bc.3a80c8","name":"","active":true,"console":"false","complete":"false","x":750,"y":380,"wires":[]},{"id":"449e32d1.88547c","type":"inject","z":"6d2f56bc.3a80c8","name":"","topic":"","payload":"123781293","payloadType":"num","repeat":"","crontab":"","once":false,"x":520,"y":220,"wires":[["3a155f79.50404"]]},{"id":"c66224eb.5e0f38","type":"inject","z":"6d2f56bc.3a80c8","name":"","topic":"","payload":"hello","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":260,"wires":[["3a155f79.50404"]]},{"id":"e29b26e8.c5f788","type":"redis-config","z":"","host":"localhost","port":"6379","dbase":"0","pass":""}]
